# Generated by Django 4.1.11 on 2023-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='defaoult', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='usercode',
            field=models.CharField(default='null', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
