# Generated by Django 4.1.11 on 2023-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myuser_address_myuser_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usercode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
